//! x86-64 (System V, AT&T syntax) code generation from the typed bytecode.
//!
//! Lowering conventions:
//! - The value stack is the hardware stack. Every value is one 8-byte
//!   quad: integers sign-extended to 64 bits, f64 as its bit pattern,
//!   bool as 0/1. The compiler's convert/convert_under instructions
//!   guarantee operands already match each instruction's static type,
//!   so no runtime tags exist.
//! - Variables are frame slots: slot k lives at -8*(k+1)(%rbp). Each
//!   frame allocates one extra hidden slot (index num_slots) used to
//!   save %rsp around calls into the C runtime, which need 16-byte
//!   alignment; our internal convention does not.
//! - Calls: arguments are already on the hardware stack (pushed left to
//!   right). The callee prologue copies them into its leading slots;
//!   the caller pops them after the call and pushes %rax if the callee
//!   returns a value.
//! - Runtime errors (division by zero, overflow, missing return) jump
//!   to stubs that call noreturn C helpers.

const std = @import("std");

const value_mod = @import("value.zig");
const Type = value_mod.Type;
const Value = value_mod.Value;
const instruction_mod = @import("instruction.zig");
const Instruction = instruction_mod.Instruction;

/// The C runtime source, written next to the generated assembly and
/// compiled together with it.
pub const runtime_c = @embedFile("../runtime/stacc_runtime.c");

pub fn emit(allocator: std.mem.Allocator, program: []const Instruction, writer: *std.Io.Writer) !void {
    // which instruction indices need a local label
    var labels = std.AutoHashMapUnmanaged(usize, void).empty;
    defer labels.deinit(allocator);
    for (program) |inst| {
        switch (inst) {
            .jump, .jump_if_false => |target| try labels.put(allocator, target, {}),
            else => {},
        }
    }

    try writer.writeAll(
        \\# generated by stacc
        \\.text
        \\.globl main
        \\
    );

    // scratch-slot offset of the frame owning each region of code:
    // main's is set by `enter`, a function's by its fn_prologue, and
    // main's is restored past the end of the function body (which is
    // the target of the jump emitted just before the prologue).
    var main_scratch: i64 = -8;
    var scratch: i64 = -8;
    var fn_end: ?usize = null;

    for (program, 0..) |inst, index| {
        if (fn_end) |end| {
            if (index == end) {
                scratch = main_scratch;
                fn_end = null;
            }
        }
        if (labels.contains(index)) {
            try writer.print(".L{d}:\n", .{index});
        }
        switch (inst) {
            .enter => |n| {
                main_scratch = -8 * (@as(i64, n) + 1);
                scratch = main_scratch;
                try writer.print(
                    \\main:
                    \\    pushq %rbp
                    \\    movq %rsp, %rbp
                    \\    subq ${d}, %rsp
                    \\
                , .{8 * (@as(i64, n) + 1)});
            },
            .fn_prologue => |f| {
                scratch = -8 * (@as(i64, f.num_slots) + 1);
                fn_end = program[index - 1].jump; // the jump-over emitted before every body
                try writer.print(
                    \\stacc_fn_{s}:
                    \\    pushq %rbp
                    \\    movq %rsp, %rbp
                    \\    subq ${d}, %rsp
                    \\
                , .{ f.name, 8 * (@as(i64, f.num_slots) + 1) });
                // copy arguments into the leading slots; arg i sits at
                // 16 + 8*(num_params-1-i)(%rbp)
                var i: u32 = 0;
                while (i < f.num_params) : (i += 1) {
                    try writer.print(
                        \\    movq {d}(%rbp), %rax
                        \\    movq %rax, {d}(%rbp)
                        \\
                    , .{ 16 + 8 * (@as(i64, f.num_params) - 1 - i), slotOffset(i) });
                }
            },
            .push_const => |v| {
                const bits: i64 = switch (v) {
                    .bool => |b| @intFromBool(b),
                    .i8 => |x| x,
                    .i32 => |x| x,
                    .i64 => |x| x,
                    .f64 => |x| @bitCast(x),
                };
                try writer.print(
                    \\    movabsq ${d}, %rax    # {f}
                    \\    pushq %rax
                    \\
                , .{ bits, v });
            },
            .load => |l| try writer.print("    pushq {d}(%rbp)    # load {s}\n", .{ slotOffset(l.slot), l.name }),
            .store => |s| try writer.print("    popq {d}(%rbp)    # store {s}\n", .{ slotOffset(s.slot), s.name }),
            .add, .sub, .mul => |t| {
                if (t == .f64) {
                    try emitBinaryF64(writer, switch (inst) {
                        .add => "addsd",
                        .sub => "subsd",
                        .mul => "mulsd",
                        else => unreachable,
                    });
                } else {
                    try writer.print(
                        \\    popq %rcx
                        \\    popq %rax
                        \\    {s} %rcx, %rax
                        \\
                    , .{switch (inst) {
                        .add => "addq",
                        .sub => "subq",
                        .mul => "imulq",
                        else => unreachable,
                    }});
                    try emitNarrowCheck(writer, t);
                    try writer.writeAll("    pushq %rax\n");
                }
            },
            .div => |t| {
                if (t == .f64) {
                    try writer.writeAll(
                        \\    movsd 8(%rsp), %xmm0
                        \\    movsd (%rsp), %xmm1
                        \\    xorpd %xmm2, %xmm2
                        \\    ucomisd %xmm2, %xmm1
                        \\    je .Lstacc_div0
                        \\    divsd %xmm1, %xmm0
                        \\    addq $8, %rsp
                        \\    movsd %xmm0, (%rsp)
                        \\
                    );
                } else {
                    try writer.writeAll(
                        \\    popq %rcx
                        \\    popq %rax
                        \\    testq %rcx, %rcx
                        \\    je .Lstacc_div0
                        \\    cqto
                        \\    idivq %rcx
                        \\
                    );
                    try emitNarrowCheck(writer, t);
                    try writer.writeAll("    pushq %rax\n");
                }
            },
            .pow => |t| {
                if (t == .f64) {
                    try writer.writeAll(
                        \\    movsd 8(%rsp), %xmm0
                        \\    movsd (%rsp), %xmm1
                        \\    addq $16, %rsp
                        \\
                    );
                    try emitHelperCall(writer, scratch, "stacc_rt_pow");
                    try writer.writeAll(
                        \\    subq $8, %rsp
                        \\    movsd %xmm0, (%rsp)
                        \\
                    );
                } else {
                    try writer.writeAll(
                        \\    popq %rsi
                        \\    popq %rdi
                        \\
                    );
                    try emitHelperCall(writer, scratch, "stacc_rt_powi");
                    try emitNarrowCheck(writer, t);
                    try writer.writeAll("    pushq %rax\n");
                }
            },
            .eq, .ne, .lt, .gt, .le, .ge => |t| {
                if (t == .f64) {
                    // lt/le compare reversed so all six use seta/setae/sete/setne
                    const swapped = inst == .lt or inst == .le;
                    try writer.writeAll(
                        \\    movsd 8(%rsp), %xmm0
                        \\    movsd (%rsp), %xmm1
                        \\    addq $16, %rsp
                        \\
                    );
                    try writer.print("    ucomisd %xmm{d}, %xmm{d}\n", .{
                        @as(u8, if (swapped) 0 else 1),
                        @as(u8, if (swapped) 1 else 0),
                    });
                    try writer.print("    {s} %al\n", .{switch (inst) {
                        .eq => "sete",
                        .ne => "setne",
                        .gt => "seta",
                        .ge => "setae",
                        .lt => "seta", // swapped operands
                        .le => "setae", // swapped operands
                        else => unreachable,
                    }});
                } else {
                    try writer.writeAll(
                        \\    popq %rcx
                        \\    popq %rax
                        \\    cmpq %rcx, %rax
                        \\
                    );
                    try writer.print("    {s} %al\n", .{switch (inst) {
                        .eq => "sete",
                        .ne => "setne",
                        .lt => "setl",
                        .gt => "setg",
                        .le => "setle",
                        .ge => "setge",
                        else => unreachable,
                    }});
                }
                try writer.writeAll(
                    \\    movzbq %al, %rax
                    \\    pushq %rax
                    \\
                );
            },
            .jump => |target| try writer.print("    jmp .L{d}\n", .{target}),
            .jump_if_false => |target| try writer.print(
                \\    popq %rax
                \\    testq %rax, %rax
                \\    jz .L{d}
                \\
            , .{target}),
            .call => |c| {
                try writer.print("    call stacc_fn_{s}\n", .{c.name});
                if (c.num_params > 0) {
                    try writer.print("    addq ${d}, %rsp\n", .{8 * @as(i64, c.num_params)});
                }
                if (c.returns_value) {
                    try writer.writeAll("    pushq %rax\n");
                }
            },
            .ret => |has_value| {
                if (has_value) {
                    try writer.writeAll("    popq %rax\n");
                }
                try writer.writeAll(
                    \\    leave
                    \\    ret
                    \\
                );
            },
            .trap => try writer.writeAll("    jmp .Lstacc_missing_return\n"),
            .pop => try writer.writeAll("    addq $8, %rsp\n"),
            .convert => |t| switch (t) {
                .f64 => try writer.writeAll(
                    \\    popq %rax
                    \\    cvtsi2sdq %rax, %xmm0
                    \\    movq %xmm0, %rax
                    \\    pushq %rax
                    \\
                ),
                .i8, .i32 => {
                    try writer.writeAll("    popq %rax\n");
                    try emitNarrowCheck(writer, t);
                    try writer.writeAll("    pushq %rax\n");
                },
                .i64 => {}, // integers are kept sign-extended; widening is free
                .bool => unreachable, // nothing coerces to bool
            },
            .convert_under => |t| {
                std.debug.assert(t == .f64); // only int -> f64 changes representation
                try writer.writeAll(
                    \\    movq 8(%rsp), %rax
                    \\    cvtsi2sdq %rax, %xmm0
                    \\    movsd %xmm0, 8(%rsp)
                    \\
                );
            },
            .print => |t| {
                switch (t) {
                    .f64 => try writer.writeAll(
                        \\    popq %rax
                        \\    movq %rax, %xmm0
                        \\
                    ),
                    else => try writer.writeAll("    popq %rdi\n"),
                }
                try emitHelperCall(writer, scratch, switch (t) {
                    .f64 => "stacc_rt_print_f64",
                    .bool => "stacc_rt_print_bool",
                    else => "stacc_rt_print_i64",
                });
            },
        }
    }

    // control flow at the end of the program jumps one past the last
    // instruction; that label is main's epilogue
    if (labels.contains(program.len)) {
        try writer.print(".L{d}:\n", .{program.len});
    }

    // main's epilogue and the shared error stubs
    try writer.writeAll(
        \\    xorl %eax, %eax
        \\    leave
        \\    ret
        \\.Lstacc_div0:
        \\    andq $-16, %rsp
        \\    call stacc_rt_div0
        \\.Lstacc_overflow:
        \\    andq $-16, %rsp
        \\    call stacc_rt_overflow
        \\.Lstacc_missing_return:
        \\    andq $-16, %rsp
        \\    call stacc_rt_missing_return
        \\
    );
}

fn slotOffset(slot: u32) i64 {
    return -8 * (@as(i64, slot) + 1);
}

/// Result is in %rax and must fit `t`; traps on overflow. Integers stay
/// canonically sign-extended, so the check is compare-after-sign-extend.
fn emitNarrowCheck(writer: *std.Io.Writer, t: Type) !void {
    switch (t) {
        .i8 => try writer.writeAll(
            \\    movsbq %al, %rcx
            \\    cmpq %rax, %rcx
            \\    jne .Lstacc_overflow
            \\
        ),
        .i32 => try writer.writeAll(
            \\    movslq %eax, %rcx
            \\    cmpq %rax, %rcx
            \\    jne .Lstacc_overflow
            \\
        ),
        .i64 => {},
        .bool, .f64 => unreachable,
    }
}

fn emitBinaryF64(writer: *std.Io.Writer, op: []const u8) !void {
    try writer.writeAll(
        \\    movsd 8(%rsp), %xmm0
        \\    movsd (%rsp), %xmm1
        \\
    );
    try writer.print("    {s} %xmm1, %xmm0\n", .{op});
    try writer.writeAll(
        \\    addq $8, %rsp
        \\    movsd %xmm0, (%rsp)
        \\
    );
}

/// Call into the C runtime: save %rsp in the frame's hidden scratch
/// slot, align to 16 bytes as the System V ABI requires, restore after.
fn emitHelperCall(writer: *std.Io.Writer, scratch_offset: i64, helper: []const u8) !void {
    try writer.print(
        \\    movq %rsp, {d}(%rbp)
        \\    andq $-16, %rsp
        \\    call {s}
        \\    movq {d}(%rbp), %rsp
        \\
    , .{ scratch_offset, helper, scratch_offset });
}

// ── tests ──────────────────────────────────────────────────────────

const compile = @import("compiler.zig").compile;

test "emits assembly with expected structure" {
    const allocator = std.testing.allocator;
    const program = try compile(allocator, "fn double(x:i64):i64 { return x + x; } print(double(21));");
    defer allocator.free(program);

    var aw = std.Io.Writer.Allocating.init(allocator);
    defer aw.deinit();
    try emit(allocator, program, &aw.writer);
    const asm_text = aw.writer.buffered();

    try std.testing.expect(std.mem.indexOf(u8, asm_text, "main:") != null);
    try std.testing.expect(std.mem.indexOf(u8, asm_text, "stacc_fn_double:") != null);
    try std.testing.expect(std.mem.indexOf(u8, asm_text, "call stacc_fn_double") != null);
    try std.testing.expect(std.mem.indexOf(u8, asm_text, "call stacc_rt_print_i64") != null);
    try std.testing.expect(std.mem.indexOf(u8, asm_text, "addq %rcx, %rax") != null);
}

test "float and comparison lowering" {
    const allocator = std.testing.allocator;
    const program = try compile(allocator, "let x = 1.5 * 2.0; print(x > 2);");
    defer allocator.free(program);

    var aw = std.Io.Writer.Allocating.init(allocator);
    defer aw.deinit();
    try emit(allocator, program, &aw.writer);
    const asm_text = aw.writer.buffered();

    try std.testing.expect(std.mem.indexOf(u8, asm_text, "mulsd %xmm1, %xmm0") != null);
    try std.testing.expect(std.mem.indexOf(u8, asm_text, "cvtsi2sdq") != null); // int 2 converts to f64
    try std.testing.expect(std.mem.indexOf(u8, asm_text, "ucomisd") != null);
    try std.testing.expect(std.mem.indexOf(u8, asm_text, "call stacc_rt_print_bool") != null);
}

test "control flow lowers to labels and jumps" {
    const allocator = std.testing.allocator;
    const program = try compile(allocator, "let i = 0; while (i < 3) { i = i + 1; }");
    defer allocator.free(program);

    var aw = std.Io.Writer.Allocating.init(allocator);
    defer aw.deinit();
    try emit(allocator, program, &aw.writer);
    const asm_text = aw.writer.buffered();

    try std.testing.expect(std.mem.indexOf(u8, asm_text, "jz .L") != null);
    try std.testing.expect(std.mem.indexOf(u8, asm_text, "jmp .L") != null);
    try std.testing.expect(std.mem.indexOf(u8, asm_text, ".Lstacc_div0:") != null);
}
